openapi: 3.0.0
info:
  title: Telegram Note API
  version: 1.0.0
tags:
  - name: note
    description: Все операции связанный с заметками
  - name: user
    description: Все операции связанные с пользователями
paths:
  /user:
    post:
      tags:
        - user
      summary: Создать нового пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostUser'
      responses:
        '201':
          description: Пользователь успешно создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Некорректные данные запроса
        '409':
          description: Такой Id чата уже существует
  /user/{chatId}:
    get:
      tags:
        - user
      summary: Получить пользователя по идентификатору чата
      parameters:
        - in: path
          name: chatId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Пользователь успешно получен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: неверные параметры запрос
        '404':
          description: Пользователь не найден
  /note:
    post:
      tags:
        - note
      summary: Создать новую заметку
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostNote'
      responses:
        '200':
          description: Заметка успешно создана
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
        '400':
          description: Некорректные данные запроса
        '403':
          description: Превышено максимальное допустимое количество символов
    put:
      tags:
        - note
      summary: Изменить заметку
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutNote'
      responses:
        '200':
          description: Заметка успешно изменена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
        '400':
          description: Некорректные данные запроса
        '403':
          description: Превышено максимальное допустимое количество символов
    get:
      tags:
        - note
      summary: Получить заметки по идентификатору чата с пагинацией
      parameters:
        - in: query
          name: chatId
          required: true
          schema:
            type: integer
            format: int64
        - in: query
          name: sizePage
          description: размер страницы
          required: true
          schema:
            type: integer
            format: int32
        - in: query
          name: offset
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Заметки успешно получены
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Note'
        '400':
          description: неверные параметры запрос
  /note/{idNote}:
    get:
      tags:
        - note
      summary: Получить заметку по идентификатору и идентификатору чата
      parameters:
        - in: path
          name: idNote
          required: true
          schema:
            type: integer
            format: int64
        - in: query
          name: chatId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Заметка успешно получена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
        '400':
          description: неверные параметры запрос
        '404':
          description: Заметка не найдена
        '403':
          description: Доступ запрещен
  /note/count:
    get:
      tags:
        - note
      summary: Получить количество заметок для идентификатора чата
      parameters:
        - in: query
          name: chatId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Количество успешно получено
          content:
            application/json:
              schema:
                type: integer
                format: int32
        '400':
          description: неверные параметры запрос
        '404':
          description: Идентификатор чата не найден
  /note/{id}:
    delete:
      tags:
        - note
      summary: Удалить заметку по идентификатору и идентификатору чата
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
        - in: query
          name: chatId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Заметка успешно удалена
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        '400':
          description: неверные параметры запрос
        '404':
          description: Заметка не найдена
        '403':
          description: Доступ запрещен
components:
  schemas:
    User:
      type: object
      properties:
        chatId:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: "Василий"
        noteList:
          type: array
          items:
            $ref: '#/components/schemas/Note'
    PostUser:
      description: DTO для регистрации (post) user
      type: object
      properties:
        chatId:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: "Василий"
    Note:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        label:
          type: string
          example: "название_заметки"
        user:
          $ref: '#/components/schemas/User'
        text:
          type: string
          example: "какой-то текст заметки"
      required:
        - id
    PutNote:
      type: object
      description: DTO объект для передачи в запрос PUT, со своими
                   необязательными параметрами
      properties:
        id:
          type: integer
          format: int64
          example: 1
        label:
          type: string
          example: "название_заметки"
        user:
          type: object
          properties:
            chatId:
              type: integer
              format: int64
              example: 123456
          required:
            - chatId
        text:
          type: string
          example: "какой-то текст заметки"
      required:
        - id
        - user
    PostNote:
      type: object
      description: DTO объект для передачи в запрос POST, со своими
        необязательными параметрами
      properties:
        label:
          type: string
          example: "название_заметки"
        user:
          type: object
          properties:
            chatId:
              type: integer
              format: int64
              example: 123456
          required:
            - chatId
        text:
          type: string
          example: "какой-то текст заметки"
      required:
        - user
        - label
        - text


